---
title: "26092019-R_markdown exploration.md"
author: "MDP"
date: "9/26/2019"
output:
  html_document:
    keep_md: true
    toc: true
    theme: cerulean
---
Set option to include specification


```{r setup, include=T}
knitr::opts_chunk$set(echo = FALSE) #false eliminates chunks of code in document
```

## Start of section

```{r}

packages <- c("rmarkdown", "DT", "tibble", "gapminder")
lapply(packages, require, character.only = TRUE) # way to require multiple packages in one call

# browseVignettes(package = "rmarkdown")

gapminder

```

```{r}
tibble::as_tibble(mtcars) # organized tibble dataframe
 # ?datatable()
DT::datatable(mtcars) # html table, estethically nice 
datatable(as_tibble(mtcars))


```

make a comment inline
<!--this is an inline comment, does not appear in output-->



## YAML modified

Settings go below the output document\
Change the teme with theme:____\
Add a table of contents with toc: true\
Make the toc float: toc_float: true.
